import os
import httpx
from typing import Any

BASE_URL = "https://www.courtlistener.com"
API_BASE = f"{BASE_URL}/api/rest/v4"


def _headers() -> dict[str, str]:
    token = os.environ.get("COURTLISTENER_TOKEN", "")
    return {"Authorization": f"Token {token}"} if token else {}


# ---------------------------------------------------------------------------
# Normalization
# ---------------------------------------------------------------------------

def _normalize_search_result(raw: dict[str, Any]) -> dict[str, Any]:
    """
    Normalize a search result object (type=o).

    Search results are *cluster* objects with nested opinion documents.
    Field names are camelCase (unlike the database REST endpoints which use
    snake_case). The snippet lives inside opinions[0], not at the top level.

    Confirmed field names from CourtListener v4 search API docs:
      caseName, cluster_id, dateFiled, citation (list), court, court_id,
      absolute_url, opinions[].id, opinions[].snippet
    """
    opinions = raw.get("opinions", [])
    lead_opinion = opinions[0] if opinions else {}
    citation_list = raw.get("citation", [])

    return {
        # cluster_id identifies the case; opinion_id identifies the specific
        # document — both are needed because forward/backward citation lookups
        # operate on opinion IDs, not cluster IDs
        "id": str(raw.get("cluster_id", "")),
        "opinion_id": str(lead_opinion.get("id", "")),
        "case_name": raw.get("caseName", ""),
        "citation": citation_list[0] if citation_list else "",
        "all_citations": citation_list,
        "court": raw.get("court", ""),
        "court_id": raw.get("court_id", ""),
        "date_filed": raw.get("dateFiled", ""),
        # snippet is nested in the opinion object; strip HTML <mark> tags
        # added by CourtListener when highlight=on is used
        "snippet": lead_opinion.get("snippet", "")[:500],
        "url": BASE_URL + raw.get("absolute_url", ""),
        "source_type": "search",
    }


def _normalize_opinion(raw: dict[str, Any], source_type: str) -> dict[str, Any]:
    """
    Normalize an opinion object returned by the database REST endpoint
    (e.g. /api/rest/v4/opinions/ or /api/rest/v4/opinions/{id}/).

    These use snake_case, unlike search results.
    NOTE: the exact field names for the opinion detail endpoint have not been
    verified against a live response — if fields are missing, check the
    OPTIONS response: GET /api/rest/v4/opinions/ with -X OPTIONS
    """
    citation_list = raw.get("citations", [])
    citation_str = citation_list[0] if citation_list else ""

    return {
        "id": str(raw.get("cluster_id") or raw.get("id", "")),
        "opinion_id": str(raw.get("id", "")),
        "case_name": raw.get("case_name", ""),
        "citation": citation_str,
        "all_citations": citation_list,
        "court": raw.get("court", ""),
        "court_id": raw.get("court_id", ""),
        "date_filed": raw.get("date_filed", ""),
        "snippet": raw.get("plain_text", "")[:500],
        "url": BASE_URL + raw.get("absolute_url", ""),
        "source_type": source_type,
    }


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

async def search_opinions(
    query: str,
    page_size: int = 10,
    filters: dict[str, str] | None = None,
) -> list[dict[str, Any]]:
    """
    Iteration 1 — broad full-text search against CourtListener opinions.
    Uses the search engine endpoint (camelCase fields, nested opinions).

    Args:
        query:      search string generated by the LLM query node
        page_size:  max results per query (keep ~10 for hackathon to stay
                    well within the 5,000/hour rate limit)
        filters:    optional extra params forwarded as GET params, e.g.
                    {"court_id": "scotus", "filed_after": "2000-01-01"}

    Returns:
        List of normalized result dicts.
    """
    params: dict[str, Any] = {
        "q": query,
        "type": "o",        # opinions / case law
        "format": "json",
        "page_size": page_size,
    }
    if filters:
        params.update(filters)

    async with httpx.AsyncClient(headers=_headers(), timeout=15.0) as client:
        resp = await client.get(f"{API_BASE}/search/", params=params)
        resp.raise_for_status()
        data = resp.json()

    return [_normalize_search_result(r) for r in data.get("results", [])]


async def get_backward_citations(opinion_id: str) -> list[dict[str, Any]]:
    """
    Iteration 2+ — cases that a given opinion *cites* (what it relied on).
    Fetches the opinion detail and resolves each entry in opinions_cited.

    Useful for tracing foundational precedent: find a relevant case, then
    walk back to the cases it was built on.

    NOTE: The exact shape of `opinions_cited` in the opinion detail response
    has not been verified. It may be a list of resource URIs, integer IDs,
    or nested objects. The integration test in test_courtlistener.py will
    catch any mismatch — run it with a live token before relying on this.

    Args:
        opinion_id: CourtListener opinion ID (opinions[0].id from search result)

    Returns:
        List of normalized result dicts with source_type="backward_citation"
    """
    async with httpx.AsyncClient(headers=_headers(), timeout=15.0) as client:
        detail_resp = await client.get(f"{API_BASE}/opinions/{opinion_id}/")
        detail_resp.raise_for_status()
        detail = detail_resp.json()

        # opinions_cited may be a list of resource URIs like
        # ["/api/rest/v4/opinions/123/"] — resolve each one.
        # Cap at 10 to avoid explosion on heavily-cited opinions.
        cited: list[str] = detail.get("opinions_cited", [])[:10]

        results = []
        for entry in cited:
            try:
                # entry is expected to be a relative URI string
                url = BASE_URL + entry if entry.startswith("/") else entry
                r = await client.get(url)
                r.raise_for_status()
                results.append(_normalize_opinion(r.json(), "backward_citation"))
            except httpx.HTTPError:
                # a single failed resolution shouldn't abort the whole batch
                continue

    return results


async def get_forward_citations(
    opinion_id: str,
    page_size: int = 10,
) -> list[dict[str, Any]]:
    """
    Iteration 2+ — opinions that *cite* this case (what came after it).
    Uses the confirmed `cited_opinion` filter on the opinions database endpoint.

    Shows how this case has been applied, distinguished, or overruled —
    i.e., the current state of the law around this decision.

    Args:
        opinion_id: CourtListener opinion ID
        page_size:  max results to return

    Returns:
        List of normalized result dicts with source_type="forward_citation"
    """
    params = {
        "cited_opinion": opinion_id,
        "format": "json",
        "page_size": page_size,
    }

    async with httpx.AsyncClient(headers=_headers(), timeout=15.0) as client:
        resp = await client.get(f"{API_BASE}/opinions/", params=params)
        resp.raise_for_status()
        data = resp.json()

    return [_normalize_opinion(r, "forward_citation") for r in data.get("results", [])]


async def verify_citations(text: str) -> list[dict[str, Any]]:
    """
    Bonus — parse and verify every legal citation in a block of text.
    Uses the CourtListener citation-lookup API (powered by Eyecite).

    Useful as a scoring guardrail: before storing a result, verify that
    its citations actually exist in CourtListener's database.

    Args:
        text: any blob of text that may contain legal citations

    Returns:
        List of citation result objects, each with:
          citation, status (200=found, 404=not found, 300=ambiguous),
          clusters (matching CourtListener cluster objects)

    Limitations:
        - Max 250 citations per request
        - Max 64,000 characters per request
        - Throttled to 60 valid citations per minute
    """
    async with httpx.AsyncClient(headers=_headers(), timeout=15.0) as client:
        resp = await client.post(
            f"{API_BASE}/citation-lookup/",
            data={"text": text},
        )
        resp.raise_for_status()

    return resp.json()
