import os
import httpx
from typing import Any

BASE_URL = "https://www.courtlistener.com"
API_BASE = f"{BASE_URL}/api/rest/v4"


def _headers() -> dict[str, str]:
    token = os.environ.get("COURTLISTENER_TOKEN", "")
    return {"Authorization": f"Token {token}"} if token else {}


# ---------------------------------------------------------------------------
# Normalization
# ---------------------------------------------------------------------------

def _normalize_search_result(raw: dict[str, Any]) -> dict[str, Any]:
    """
    Normalize a search result object (type=o).

    Search results are *cluster* objects with nested opinion documents.
    Field names are camelCase (unlike the database REST endpoints which use
    snake_case). The snippet lives inside opinions[0], not at the top level.

    Confirmed field names from CourtListener v4 search API docs:
      caseName, cluster_id, dateFiled, citation (list), court, court_id,
      absolute_url, opinions[].id, opinions[].snippet
    """
    opinions = raw.get("opinions", [])
    lead_opinion = opinions[0] if opinions else {}
    citation_list = raw.get("citation", [])

    return {
        # cluster_id identifies the case; opinion_id identifies the specific
        # document — both are needed because forward/backward citation lookups
        # operate on opinion IDs, not cluster IDs
        "id": str(raw.get("cluster_id", "")),
        "opinion_id": str(lead_opinion.get("id", "")),
        "case_name": raw.get("caseName", ""),
        "citation": citation_list[0] if citation_list else "",
        "all_citations": citation_list,
        "court": raw.get("court", ""),
        "court_id": raw.get("court_id", ""),
        "date_filed": raw.get("dateFiled", ""),
        # snippet is nested in the opinion object; strip HTML <mark> tags
        # added by CourtListener when highlight=on is used
        "snippet": lead_opinion.get("snippet", "")[:500],
        "url": BASE_URL + raw.get("absolute_url", ""),
        "source_type": "search",
    }


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

async def search_opinions(
    query: str,
    page_size: int = 10,
    filters: dict[str, str] | None = None,
) -> list[dict[str, Any]]:
    """
    Iteration 1 — broad full-text search against CourtListener opinions.
    Uses the search engine endpoint (camelCase fields, nested opinions).

    Args:
        query:      search string generated by the LLM query node
        page_size:  max results per query (keep ~10 for hackathon to stay
                    well within the 5,000/hour rate limit)
        filters:    optional extra params forwarded as GET params, e.g.
                    {"court_id": "scotus", "filed_after": "2000-01-01"}

    Returns:
        List of normalized result dicts.
    """
    params: dict[str, Any] = {
        "q": query,
        "type": "o",        # opinions / case law
        "format": "json",
        "page_size": page_size,
    }
    if filters:
        params.update(filters)

    async with httpx.AsyncClient(headers=_headers(), timeout=15.0) as client:
        resp = await client.get(f"{API_BASE}/search/", params=params)
        resp.raise_for_status()
        data = resp.json()

    return [_normalize_search_result(r) for r in data.get("results", [])]


async def _resolve_opinion_with_cluster(
    client: httpx.AsyncClient,
    opinion_url: str,
) -> dict[str, Any] | None:
    """
    Fetch an opinion object and its parent cluster in parallel, then merge
    them into a single normalized result.

    Opinion object provides: opinion_id, snippet (plain_text)
    Cluster object provides: case_name, citations, court, date_filed, absolute_url

    Returns None if either request fails, so the caller can skip it cleanly.
    """
    import asyncio

    try:
        opinion_resp, = await asyncio.gather(client.get(opinion_url))
        opinion_resp.raise_for_status()
        opinion = opinion_resp.json()

        cluster_id = opinion.get("cluster_id")
        if not cluster_id:
            return None

        cluster_resp = await client.get(f"{API_BASE}/clusters/{cluster_id}/")
        cluster_resp.raise_for_status()
        cluster = cluster_resp.json()
    except httpx.HTTPError:
        return None

    # Citations on the cluster come back as nested objects:
    # [{"volume": 410, "reporter": "U.S.", "page": "113", "type": 1}, ...]
    # Flatten to strings matching the shape from search results.
    raw_citations = cluster.get("citations", [])
    citation_strs: list[str] = []
    for c in raw_citations:
        if isinstance(c, str):
            citation_strs.append(c)
        elif isinstance(c, dict):
            vol = c.get("volume", "")
            rep = c.get("reporter", "")
            page = c.get("page", "")
            if vol and rep and page:
                citation_strs.append(f"{vol} {rep} {page}")

    return {
        "id": str(cluster_id),
        "opinion_id": str(opinion.get("id", "")),
        "case_name": cluster.get("case_name", ""),
        "citation": citation_strs[0] if citation_strs else "",
        "all_citations": citation_strs,
        "court": cluster.get("court_id", ""),
        "court_id": cluster.get("court_id", ""),
        "date_filed": cluster.get("date_filed", ""),
        "snippet": opinion.get("plain_text", "")[:500],
        "url": BASE_URL + cluster.get("absolute_url", opinion.get("absolute_url", "")),
        "source_type": "backward_citation",
    }


async def get_backward_citations(opinion_id: str) -> list[dict[str, Any]]:
    """
    Iteration 2+ — cases that a given opinion *cites* (what it relied on).
    Fetches the opinion detail, resolves each cited opinion URL, and for each
    also fetches the parent cluster to get full metadata (case_name, citations,
    court, date_filed). Opinion + cluster are fetched in parallel per result.

    Args:
        opinion_id: CourtListener opinion ID (opinions[0].id from search result)

    Returns:
        List of fully normalized result dicts with source_type="backward_citation"
    """
    import asyncio

    async with httpx.AsyncClient(headers=_headers(), timeout=15.0) as client:
        detail_resp = await client.get(f"{API_BASE}/opinions/{opinion_id}/")
        detail_resp.raise_for_status()
        detail = detail_resp.json()

        # opinions_cited is a list of full URL strings, confirmed by tests:
        # ["https://www.courtlistener.com/api/rest/v4/opinions/672370/"]
        # Cap at 10 to avoid explosion on heavily-cited opinions.
        cited_urls: list[str] = detail.get("opinions_cited", [])[:10]

        # Resolve all cited opinions in parallel
        tasks = [_resolve_opinion_with_cluster(client, url) for url in cited_urls]
        resolved = await asyncio.gather(*tasks)

    return [r for r in resolved if r is not None]


async def get_forward_citations(
    opinion_id: str,
    page_size: int = 10,
) -> list[dict[str, Any]]:
    """
    Iteration 2+ — opinions that *cite* this case (what came after it).
    Uses the search endpoint with `cites:(id)` syntax — same engine as
    search_opinions, so the response shape is identical (cluster + nested opinions).

    Shows how this case has been applied, distinguished, or overruled —
    i.e., the current state of the law around this decision.

    Args:
        opinion_id: CourtListener opinion ID
        page_size:  max results to return

    Returns:
        List of normalized result dicts with source_type="forward_citation"
    """
    # `cites` is a documented search field: "All of the item IDs that cite an opinion."
    # Use the search endpoint with `cites:ID` syntax (no parentheses — those are
    # for multi-term grouping, not needed for a single numeric ID).
    # The REST opinions endpoint does NOT support a cited_opinion filter.
    params = {
        "q": f"cites:{opinion_id}",
        "type": "o",
        "page_size": page_size,
    }

    async with httpx.AsyncClient(headers=_headers(), timeout=15.0) as client:
        resp = await client.get(f"{API_BASE}/search/", params=params)
        resp.raise_for_status()
        data = resp.json()

    results = [_normalize_search_result(r) for r in data.get("results", [])[:page_size]]
    for r in results:
        r["source_type"] = "forward_citation"
    return results


async def verify_citations(text: str) -> list[dict[str, Any]]:
    """
    Bonus — parse and verify every legal citation in a block of text.
    Uses the CourtListener citation-lookup API (powered by Eyecite).

    Useful as a scoring guardrail: before storing a result, verify that
    its citations actually exist in CourtListener's database.

    Args:
        text: any blob of text that may contain legal citations

    Returns:
        List of citation result objects, each with:
          citation, status (200=found, 404=not found, 300=ambiguous),
          clusters (matching CourtListener cluster objects)

    Limitations:
        - Max 250 citations per request
        - Max 64,000 characters per request
        - Throttled to 60 valid citations per minute
    """
    async with httpx.AsyncClient(headers=_headers(), timeout=15.0) as client:
        resp = await client.post(
            f"{API_BASE}/citation-lookup/",
            data={"text": text},
        )
        resp.raise_for_status()

    return resp.json()
